site_name: lernOS Change Management
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen: 1-0-Grundlagen.md
    - Lernpfad: 2-0-Lernpfad.md
    - Anhang: 3-0-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/change/blob/master/de/build/change-guide.pdf
      - Word-Version: https://github.com/cogneon/change/blob/master/de/build/change-guide.docx
      - HTML-Version: https://github.com/cogneon/change/blob/master/de/build/change-guide.html
      - E-Book (epub): https://github.com/cogneon/change/blob/master/de/build/change-guide.epub
      - E-Book (mobi): https://github.com/cogneon/change/blob/master/de/build/change-guide.mobi
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/matomo.js

repo_name: 'cogneon/lernos-template'
repo_url: 'https://github.com/cogneon/lernos-template'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    generator: false

copyright: cogneon.de/impressum

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - rss:
      abstract_chars_count: -1  # -1 for full content
